pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Diegomuu/TingesoEv1']])
                dir("kartFro"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("kartFro"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t diegomuu/kartFro ."
                            bat "docker push diegomuu/kartFro"
                        }
                    }                    
                }
            }
        }
    }
}