version: "3.8"

services:
  # Base de datos MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - backend-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456  
      MYSQL_DATABASE: kart
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  # Backend services
  backend1:
    image: diegomuu/kart-back:latest
    container_name: backend1
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=kart
    depends_on:
      - mysql
    networks:
      - backend-network

  backend2:
    image: diegomuu/kart-back:latest
    container_name: backend2
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=kart
    depends_on:
      - mysql
    networks:
      - backend-network

  backend3:
    image: diegomuu/kart-back:latest
    container_name: backend3
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=kart
    depends_on:
      - mysql
    networks:
      - backend-network

  # Frontend services
  frontend1:
    image: diegomuu/kart-front:latest
    container_name: frontend1
    networks:
      - frontend-network

  frontend2:
    image: diegomuu/kart-front:latest
    container_name: frontend2
    networks:
      - frontend-network

  frontend3:
    image: diegomuu/kart-front:latest
    container_name: frontend3
    networks:
      - frontend-network

  # Nginx para balanceo de carga en el frontend
  nginx-frontend:
    image: nginx:latest
    container_name: nginx-frontend
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx para balanceo de carga en el backend
  nginx-backend:
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  mysql_data: